### ISSUE TITLE
検索履歴をタップすると落ちるバグ

### ISSUE THREAD

**Issue by Yuki014** [jagsc/ABC2019sConferenceApp#13]
検索履歴をタップすると以下のエラーが発生して落ちる

2019-05-06 14:12:51.552 24018-24018/com.example.abc2019sconferenceapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.abc2019sconferenceapp, PID: 24018
    java.lang.IllegalStateException: binding.textView.searchBar must not be null
        at com.example.abc2019sconferenceapp.fragment.search.SearchFragment$onCreateView$2$1.onClick(SearchFragment.kt:91)
        at com.example.abc2019sconferenceapp.fragment.search.SearchHistoryViewHolder$bindTo$1.onClick(SearchHistoryViewHolder.kt:29)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24710)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:251)
        at android.app.ActivityThread.main(ActivityThread.java:6572)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by Yuki014** [comment]
構文ミスによるエラーだったので解決
