### ISSUE TITLE
検索結果の詳細から他項目に飛ぶと落ちる

### ISSUE THREAD

**Issue by zyundamochi080** [jagsc/ABC2019sConferenceApp#21]
検索した結果のどれかを開いてそこから下のタブでtimelineとかに飛ぶとアプリが落ちる
Log
```E/AndroidRuntime: FATAL EXCEPTION: main
    Process: jagsc.jp.abc2019Sconferenceapp, PID: 14005
    java.lang.IllegalStateException: Fragment SearchFragment{6f5ac19} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:696)
        at jagsc.jp.abc2019Sconferenceapp.fragment.search.SearchFragment$onCreateView$2.invokeSuspend(SearchFragment.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:6217)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)```

**Comment by zyundamochi080** [comment]
おま環じゃないか誰かチェックお願いします...

**Comment by prprhyt** [comment]
僕の環境でも確認できました。
Mate9(Android 9.0) 743ebb98

**Comment by prprhyt** [comment]
https://github.com/jagsc/ABC2019sConferenceApp/blob/743ebb9841ccc123f7af608209ad1889371863fb/app/src/main/java/jagsc/jp/abc2019Sconferenceapp/fragment/search/SearchFragment.kt#L82

ここで落ちてる。
